### ISSUE TITLE
Doesn't work in Clojure 1.8.0

### ISSUE THREAD

**Issue by smahood** [eggsyntax/datawalk#1]
It looks like there's a problem with `print.cljc` when trying to run in Clojure 1.8.0 - I get an error message `CompilerException java.lang.RuntimeException: Unable to resolve symbol: seqable? in this context, compiling:(datawalk/print.cljc:99:12)`

This isn't a real problem for me as 1.9 is where I plan to use this, I noticed it because I was testing with a new project and lein brings 1.8 in by default. Thought I should let you now though.

**Comment by eggsyntax** [comment]
Thanks! I came across it the same way the other day (had been using 1.9 but
tried it in a new 1.8 lein project), so it's already fixed -- just rolled
my own `is-sequable?` fn for backward compatibility. There are a few other
improvements since then as well.

Thanks so much for giving it a try!

**Comment by mmower** [comment]
How do you get this fixed version?

I'm including 0.1.4 and getting the same error about seqable? now.

**Comment by eggsyntax** [comment]
Hi Matt, 
My guess is that you have an old version in your Maven repository. If you `rm -rf ~/.m2/repository/datawalk`, that will tell lein to redownload, and you should be good to go. Please let me know if that doesn't work, and I'll look into it. It's conceivable, although hopefully unlikely, that I deployed the wrong version to clojars.

**Comment by mmower** [comment]
Deleted and re-downloaded but, alas, same error.

**Comment by eggsyntax** [comment]
Damn! OK, I'll push a corrected version to clojars ASAP & let you know here when it's done.

**Comment by eggsyntax** [comment]
@mmower will you kindly delete your local cache & give it another try? Looks like I merged from a branch that still had a call to `seqable?` and overlooked it.

**Comment by mmower** [comment]
A ha! I think you have cracked it sir, thank you :)
