### ISSUE TITLE
ReferenceError: datawalk is not defined

### ISSUE THREAD

**Issue by mmower** [eggsyntax/datawalk#4]
To quit, type: :cljs/quit
dev:cljs.user=> (require '[datawalk.core :as dw :refer [look-at w]])
nil
dev:cljs.user=> (look-at @re-frame.db/app-db)
#object[ReferenceError ReferenceError: datawalk is not defined]
nil
dev:cljs.user=> (look-at {})
#object[ReferenceError ReferenceError: datawalk is not defined]
nil

Dependencies:
[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.946"]
                 [com.rpl/specter "1.0.4"]
                 [fipp "0.6.10"]
                 [reagent "0.7.0"]
                 [re-frame "0.10.2"]
                 [re-frisk "0.5.0"]
                 [org.clojure/core.async "0.3.443"]
                 [re-com "2.1.0"]
                 [frankiesardo/linked "1.2.9"]
                 [re-frame-datatable "0.6.0"]
                 [sandbags/aido "0.3.1"]
                 [datawalk "0.1.4-SNAPSHOT"]
                 [klang "0.5.9"]
                 [inflections "0.13.0"]

**Comment by eggsyntax** [comment]
Yikes! Very strange. I'm stuck reinstalling my OS at the moment, but I'll take a look at that tomorrow for sure.

**Comment by eggsyntax** [comment]
So have you been entirely unable to use datawalk from cljs?

**Comment by mmower** [comment]
Unfortunately, after you fixed the problem with `seqable?`, I was able to `require` it but got no further.

**Comment by eggsyntax** [comment]
This is turning out to be a bit tricky -- I believe it's a dependency issue with cljs. I'm going to have to come back to it later today. FWIW, though, I found that I could ignore the error and continue to use datawalk as usual -- so if you're interested in exploring datawalk, hopefully you won't need to wait on this fix to do so.

I suggest bumping your dependency to `[datawalk "0.1.5-SNAPSHOT"]` just to make sure you've got the latest. If you're able to do so, you might also want to bump your clj dependency to one of the 1.9 betas.

Sorry for the hassle! I'll resolve it as soon as possible.

**Comment by eggsyntax** [comment]
Resolved in 0.1.9. LMK if you have any further issues. Thanks for your patience!
